### ISSUE TITLE
Make nicer pricing page

### ISSUE THREAD

**Issue by tnurse18** [WPI-LNL/website#2]
I think it would be a good idea to create a nice landing page for the pricing information on the static site. Currently we just redirect to a PDF. I think we can do better than that!

**Comment by rrlapointe** [comment]
I agree that this would be nice, but I would like to point out that this would add a *fifth* thing that needs to updated when a price is changed. We already need to update the following every time a price changes:

- LNLDB
- work order wizard
- basic pricelist
- full pricelist

Also, a client can use the work order wizard to see how much an event would cost without submitting it. Would this new web page look similar to the work order wizard, but without the automatic total calculation? If so, is the extra value provided by this new page (beyond what the pricelists and work order wizard already provide) worth the effort to develop and maintain it? Just giving my 2¢.

**Comment by tnurse18** [comment]
The prices shouldn't be changing all that often in the first place. However you do bring up a fair point in that we probably don't want to have too many things that would need to be updated if they do. That being said, I think a landing page would still be more user friendly than the PDFs. Yes, you can always play around with the work order wizard to figure out prices, however it involves many more clicks (and requires a login if I remember correctly) to get to the prices themselves. Furthermore, I'm not sure how clear it is to new customers that they can do that.

I was thinking this would be a fairly simple page, not quite as advanced as the work order wizard. In other words, it probably wouldn't have automatic total calculations. Likely just the prices. Although, I suppose we could sync it with the prices in the LNLDB if we really wanted to get fancy.
